keys:
  - &admin_jdgt age1zrj4vu5qzhj8ae7ey0r44e9cnryzll7naj3z7dx8nmcdlu82wsxqdtyfy4
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jdgt
