keys:
  - &admin_jdgt age1pjwfzzjk85qejf5k6xlazjzy8u3pmaq5qk2ncqdg9p5atl0dgaxq2kveqx
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_jdgt
