{
  imports = [
    ./hardware
    ./packages
    ./programs
    ./base16.nix
    ./boot.nix
    ./console.nix
    ./home-manager.nix
    ./laptop.nix
    ./locale.nix
    ./networking.nix
    ./nix.nix
    ./nixpkgs.nix
    ./security.nix
    ./services.nix
    ./users.nix
  ];
}
